#
# SPDX-License-Identifier: Apache-2.0
#

repository:
  name: firefly-helm-charts
  description: Firefly Helm Charts
  homepage: https://github.com/hyperledger/firefly-helm-charts
  default_branch: main
  has_downloads: true
  has_issues: true
  has_projects: true
  has_wiki: true
  archived: false
  private: false
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
