fullnameOverride: ""

service:
  type: ClusterIP
  port: 5000

podAnnotations: {}

imagePullSecrets: []

podSecurityContext: {}

securityContext: {}

extraEnv: []

initContainers: ""
extraContainers: ""
extraVolumeClaimTemplates: ""

resources: {}

nodeSelector: {}

affinity: {}

tolerations: {}

persistentVolume:
  accessModes:
    - ReadWriteOnce
  annotations: {}
  size: 2Gi
  storageClass: ""

image:
  repository: ghcr.io/hyperledger/firefly-evmconnect
  pullPolicy: IfNotPresent
  # tag: ""

# see https://github.com/hyperledger/firefly-evmconnect/blob/main/config.md for more info
config:
  jsonRpcUrl: ""

  log:
    level: debug
    jsonEnabled: false

  confirmations:
    required: 0
    # blockQueueLength: 50
    # staleReceiptTimeout: 1m
    # notificationQueueLength: 50

  persistence:
    type: leveldb
    leveldb:
      maxHandles: 100
      syncWrites: false
    templateOverride: ""

  connector: |
    url: {{ .Values.config.jsonRpcUrl | quote }}

  policyEngine: ""

  policyLoop: {}

  transactions: {}

  webhooks: {}

  eventstreams: {}
